apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: hq7w55ohk-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9a313d5b40.9sez.p3.openshiftapps.com/rhtap/rhtap-qe:07b80ccb786f3f48148d8d4d4f52ef94e375b41a@sha256:568866c71698a532c18ef0c2f29de602e49f378367f495a7d581d4b85ac53d64
        name: container-image  
